[package]
name = "sepolicy-inject-rs"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "sepolicy-inject-rs"
path = "src/main.rs"

[lib]
name = "sepolicy"
path = "src/lib.rs"

[dependencies]
cxx = "1.0.192"

[build-dependencies]
cc = "1.2.49"
cxx-build = "1.0.192"
cxx-gen = "0.7.192"
